const express = require('express')
require('dotenv').config()
const cors = require('cors')
const { NivelAPI } = require("./routes/Nivel.routes")
const { VigenciaLineaInvestigacionAPI } = require("./routes/VigenciaLineaInvestigacion.routes")
const { JcrAPI } = require("./routes/Jcr.routes")
const { ProgramaAPI } = require("./routes/Programa.routes")
const { ClasificacionProductoAPI } = require("./routes/ClasificacionProducto.routes")
const { GrupoAPI } = require("./routes/Grupo.routes")
const { TipoIdentificacionAPI } = require("./routes/TipoIdentificacion.routes")
const { TipoVinculacionAPI } = require("./routes/TipoVinculacion.routes")
const { TipoProductoAPI } = require("./routes/TipoProducto.routes")
const { IntegrantesProyectoAPI } = require("./routes/IntegrantesProyecto.routes")
const { ProductoAPI } = require("./routes/Producto.routes")
const { TipoConvenioAPI } = require("./routes/TipoConvenio.routes")
const { ClasificacionGrupoAPI } = require("./routes/ClasificacionGrupo.routes")
const { VinculacionGrupoAPI } = require("./routes/VinculacionGrupo.routes")
const { GeneroAPI } = require("./routes/Genero.routes")
const { SjrAPI } = require("./routes/Sjr.routes")
const { ClasConvMincienciasAPI } = require("./routes/ClasConvMinciencias.routes")
const { ConvocatoriaInvestigadorAPI } = require("./routes/ConvocatoriaInvestigador.routes")
const { PostulacionAPI } = require("./routes/Postulacion.routes")
const { EstadoProductoAPI } = require("./routes/EstadoProducto.routes")
const { ConveniosAPI } = require("./routes/Convenios.routes")
const { IntegranteAPI } = require("./routes/Integrante.routes")
const { ProyectosAPI } = require("./routes/Proyectos.routes")
const { ConvocatoriaAPI } = require("./routes/Convocatoria.routes")
const { FacultadAPI } = require("./routes/Facultad.routes")
const { TipoIntegranteAPI } = require("./routes/TipoIntegrante.routes")
const { RolAPI } = require("./routes/Rol.routes")
const { TipoInvestigacionAPI } = require("./routes/TipoInvestigacion.routes")
const { EstadoProyectoAPI } = require("./routes/EstadoProyecto.routes")
const { CatConvoMincienciasAPI } = require("./routes/CatConvoMinciencias.routes")
const { LineaInvestigacionAPI } = require("./routes/LineaInvestigacion.routes")
const app = express()
app.use(cors())
app.use(express.static("./storageFiles"))
app.use(express.json())
NivelAPI(app)
VigenciaLineaInvestigacionAPI(app)
JcrAPI(app)
ProgramaAPI(app)
ClasificacionProductoAPI(app)
GrupoAPI(app)
TipoIdentificacionAPI(app)
TipoVinculacionAPI(app)
TipoProductoAPI(app)
IntegrantesProyectoAPI(app)
ProductoAPI(app)
TipoConvenioAPI(app)
ClasificacionGrupoAPI(app)
VinculacionGrupoAPI(app)
GeneroAPI(app)
SjrAPI(app)
ClasConvMincienciasAPI(app)
ConvocatoriaInvestigadorAPI(app)
PostulacionAPI(app)
EstadoProductoAPI(app)
ConveniosAPI(app)
IntegranteAPI(app)
ProyectosAPI(app)
ConvocatoriaAPI(app)
FacultadAPI(app)
TipoIntegranteAPI(app)
RolAPI(app)
TipoInvestigacionAPI(app)
EstadoProyectoAPI(app)
CatConvoMincienciasAPI(app)
LineaInvestigacionAPI(app)
const port = process.env.PORT
app.listen(port, () => {
  console.log(`Servidor corriendo en http: // localhost: ${port}`)
})