const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: null,
      comment: null,
      primaryKey: true,
      field: "id",
      autoIncrement: false,
    },
    id_categoria_investigador: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_categoria_investigador",
      autoIncrement: false,
      references: {
        key: "id",
        model: "convocatoria_investigador_model",
      },
    },
    id_genero: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_genero",
      autoIncrement: false,
      references: {
        key: "id",
        model: "genero_model",
      },
    },
    id_tipo_ident: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_tipo_ident",
      autoIncrement: false,
      references: {
        key: "id",
        model: "tipo_identificacion_model",
      },
    },
    num_ident: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "num_ident",
      autoIncrement: false,
    },
    primer_nom: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "primer_nom",
      autoIncrement: false,
    },
    seg_nom: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "seg_nom",
      autoIncrement: false,
    },
    primer_ape: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "primer_ape",
      autoIncrement: false,
    },
    seg_ape: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "seg_ape",
      autoIncrement: false,
    },
    url_cvlac: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "url_cvlac",
      autoIncrement: false,
    },
    google_schoolar: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "google_schoolar",
      autoIncrement: false,
    },
    modelo_orcid: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "modelo_orcid",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "integrante",
    comment: "",
    indexes: [],
    timestamps: false,
    underscored: true,
    freezeTableName: true,
    schema: "public",
  };
  const IntegranteModel = sequelize.define(
    "IntegranteModel",
    attributes,
    options
  );
  return IntegranteModel;
};
