const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: null,
      comment: null,
      primaryKey: true,
      field: "id",
      autoIncrement: false,
    },
    id_tipo_producto: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_tipo_producto",
      autoIncrement: false,
      references: {
        key: "id",
        model: "tipo_producto_model",
      },
    },
    id_proyecto: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_proyecto",
      autoIncrement: false,
      references: {
        key: "id",
        model: "proyectos_model",
      },
    },
    id_estado_producto: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_estado_producto",
      autoIncrement: false,
      references: {
        key: "id",
        model: "estado_producto_model",
      },
    },
    id_integrante_principal: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_integrante_principal",
      autoIncrement: false,
      references: {
        key: "id",
        model: "integrante_model",
      },
    },
    nombre: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "nombre",
      autoIncrement: false,
    },
    tipo_articulo: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "tipo_articulo",
      autoIncrement: false,
    },
    doi: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "doi",
      autoIncrement: false,
    },
    pais: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "pais",
      autoIncrement: false,
    },
    ISSN: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "ISSN",
      autoIncrement: false,
    },
    url_producto: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "url_producto",
      autoIncrement: false,
    },
    descripcion: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "descripcion",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "producto",
    comment: "",
    indexes: [],
    timestamps: false,
    underscored: true,
    freezeTableName: true,
    schema: "public",
  };
  const ProductoModel = sequelize.define("ProductoModel", attributes, options);
  return ProductoModel;
};
