const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
  const attributes = {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: null,
      comment: null,
      primaryKey: true,
      field: "id",
      autoIncrement: false,
    },
    id_estado_proyecto: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_estado_proyecto",
      autoIncrement: false,
      references: {
        key: "id",
        model: "estado_proyecto_model",
      },
    },
    id_convenios: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_convenios",
      autoIncrement: false,
      references: {
        key: "id",
        model: "convenios_model",
      },
    },
    id_tipo_investigacion: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "id_tipo_investigacion",
      autoIncrement: false,
      references: {
        key: "id",
        model: "tipo_investigacion_model",
      },
    },
    titulo: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "titulo",
      autoIncrement: false,
    },
    centro_costo: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "centro_costo",
      autoIncrement: false,
    },
    fecha_inicio: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "fecha_inicio",
      autoIncrement: false,
    },
    fecha_fin: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "fecha_fin",
      autoIncrement: false,
    },
    duracion_mes: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "duracion_mes",
      autoIncrement: false,
    },
    resumen: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "resumen",
      autoIncrement: false,
    },
    objectivo_general: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "objectivo_general",
      autoIncrement: false,
    },
    objectivos_especificos: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "objectivos_especificos",
      autoIncrement: false,
    },
    justificacion: {
      type: DataTypes.CHAR,
      allowNull: true,
      defaultValue: null,
      comment: null,
      primaryKey: false,
      field: "justificacion",
      autoIncrement: false,
    },
  };
  const options = {
    tableName: "proyectos",
    comment: "",
    indexes: [],
    timestamps: false,
    underscored: true,
    freezeTableName: true,
    schema: "public",
  };
  const ProyectosModel = sequelize.define(
    "ProyectosModel",
    attributes,
    options
  );
  return ProyectosModel;
};
